[build]
  command = "npm run build"
  publish = "dist"

[production]
  command = "npm run start"
  targetPort = 3000
  port = 8888
  framework = "nodejs"

[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 3888
  framekwork = "nodejs"